Start from the dataset kickstarter-14-04, take out the unnecessary columsn that I don't know why are there:

In [49]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import nltk
from nltk.corpus import stopwords
import string 
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re 
from collections import Counter
import ast
import glob

In [50]:
campaigns = pd.read_csv('raw_kickstarter.csv', index_col=0)
campaigns

,url,title,description,pledged,usd_pledged,converted_pledged_amount,goal,currency
0,https://www.kickstarter.com/projects/thetruthb...,NaN,The PROBLEM: So much entertainment today pushe...,71123.0,71123.0,61607,48000.0,USD
1,https://www.kickstarter.com/projects/99625582/...,NaN,Millions of American college students have stu...,65318.0,65318.0,56579,61500.0,USD
2,https://www.kickstarter.com/projects/distortre...,Cartoon Network Alphabet Pins,Full A-Z Set I'm launching this set to show my...,462.0,462.0,400,8000.0,USD
3,https://www.kickstarter.com/projects/jordym/th...,The Balloon - a short film,"On a sleepy summer afternoon, we stared into t...",5137.0,5137.0,4449,15000.0,USD
4,https://www.kickstarter.com/projects/trans-mov...,NaN,48 hours of pledge matching! Amazing news! Two...,50640.0,50640.0,43865,50000.0,USD
...,...,...,...,...,...,...,...,...
8390,https://www.kickstarter.com/projects/zerwcolla...,ZerwCollab: Your AI-Powered App Builder in Sec...,🚀 What If You Could Launch a Website or App… U...,2128.0,2128.0,1823,35900.0,USD
8391,https://www.kickstarter.com/projects/jacobzirk...,VFX Oasis: Free VFX Assets and Footage,What is VFX Oasis? VFX Oasis is an industry fo...,580.0,580.0,496,6000.0,USD
8392,https://www.kickstarter.com/projects/153189407...,Sharp X - Edge Gadget,Kickstarter Project Story – USA-Market Sharpen...,857.0,857.0,734,7800.0,USD
8393,https://www.kickstarter.com/projects/diyengine...,Steady Shot Bot: Hyperlapse + Steadycam + Auto...,"Why As a hobbyist, I recently found myself wan...",6645.0,6645.0,5693,310000.0,USD
8394,https://www.kickstarter.com/projects/brilliant...,Covert Docking Headset | 008 | Hidden yet acce...,BRILLIANT BUDS INTRODUCES THE COVERT WIRELESS ...,3974.0,3974.0,3404,18000.0,USD

### as a very first step we add the categories to each project

In [ ]:

folder_path = "Kickstarter_2026-03-12T03_20_26_556Z"

files = glob.glob(f"{folder_path}/*.csv")

print("Number of files found:", len(files))

dfs = []

for file in files:
    print("Loading:", file)
    df_temp = pd.read_csv(file)
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)



url_to_category = {}
for _, row in df.iterrows():
    parsed = ast.literal_eval(row['category'])
    parent_name = parsed.get('parent_name') or parsed.get('name')
    url_parsed = ast.literal_eval(row['urls'])
    project_url = url_parsed['web']['project']
    url_to_category[project_url] = parent_name


campaigns['category'] = campaigns['url'].map(url_to_category)

print(f"Matched: {campaigns['category'].notna().sum()} / {len(campaigns)}")
print(campaigns['category'].value_counts())

Number of files found: 85
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter001.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter002.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter003.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter004.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter005.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter006.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter007.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter008.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter009.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter010.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter011.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter012.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter013.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter014.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter015.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter016.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter017.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter018.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter019.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter020.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter021.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter022.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter023.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter024.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter025.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter026.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter027.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter028.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter029.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter030.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter031.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter032.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter033.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter034.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter035.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter036.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter037.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter038.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter039.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter040.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter041.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter042.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter043.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter044.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter045.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter046.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter047.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter048.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter049.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter050.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter051.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter052.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter053.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter054.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter055.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter056.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter057.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter058.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter059.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter060.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter061.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter062.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter063.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter064.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter065.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter066.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter067.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter068.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter069.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter070.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter071.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter072.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter073.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter074.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter075.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter076.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter077.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter078.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter079.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter080.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter081.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter082.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter083.csv
Loading: Kickstarter_2026-03-12T03_20_26_556Z\Kickstarter084.csv
Final shape: (268539, 42)
Matched: 7354 / 7354
category
Film & Video    2011
Technology      1489
Games           1422
Music           1218
Publishing      1214
Name: count, dtype: int64

take out the unnecessary columns, add the reached one and classify as success or failure (maybe it's already in the initial dataset but honestly I don't remember)

In [56]:
campaigns['reached'] = (campaigns['pledged'] / campaigns['goal']) * 100

median_reached = campaigns['reached'].median()
campaigns['status'] = campaigns['reached'].apply(lambda x: 1 if x >= median_reached else 0)

Preprocessing: usual preprocessing stuff like lowercasing, taking out links, only keepin alpha numeric characters, tokenizing the words, and taking out the english stopwords, also took out the words that are less than 2 characters

In [58]:
def preprocess(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+', ' ', text)
    text_p = "".join([char for char in text if char.isalnum() or char.isspace()])
    
    words = word_tokenize(text_p) 
    
    
    stop_words = stopwords.words('english')
    words = [w for w in words if w not in stop_words and len(w) > 2]
    filtered_words = [word for word in words if word not in stop_words] 
    
    return filtered_words  

campaigns['description_processed'] = campaigns['description'].apply(preprocess)

How do we decide which stopwords to include beside the 'normal' stopwords? We also want to include words that are very generic, not informative at all and coudl potentially appear in any kind of campaign, regardless of the topics in it (some examples could be the words 'kickstarter', campaign, etc etc)
Initially I thought TF-IDF would make sense but it doesn't actually, because TF-IDF both depends on how frequent a word is in each document and how frequent are documents that contain that words in the whole set of documents. (also you cannot average the TF-IDF of a word and pick the ones with lowest value because a rare word, which we wanna keep, could end up having a low TF-IDF value if it appears in few documents but many time in those few documents)
So potentially we can just use document frequency, meaning if the word appears in > alpha% of documents, we count it as a stopword?

Also quick sidenote: Other methods like BytePair encoding, WordPiece or SentencePiece are not really useful here because they look at subwords, and for example if we get 'kickstarter' and split it into kick and starter, then we might consider to keep kick because it makes sense with sport but we might not have any document where the word is present for real

This below just basically gives a counter of the document frequency of each token in our whole corpus of all the descriptions

We apply lemmatization (I think probably better than stemming since it returns the lemma version of the word, instead of just cutting the ending of the word). We apply it now, before taking out the domain specific stopwords, because otherwise we could end up having to account for different versions of the same stopword (example: project vs projects)

In [60]:
lemmatizer = WordNetLemmatizer()

campaigns['lemmatized'] = campaigns['description_processed'].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words])

In [61]:
docs = campaigns['lemmatized']
N = len(docs)

df_counter = Counter()

for doc in docs:
    df_counter.update(set(doc))

df_table = pd.DataFrame({
    'word': list(df_counter.keys()),
    'doc_freq': list(df_counter.values())
})

df_table['doc_freq_ratio'] = df_table['doc_freq'] / N
df_table = df_table.sort_values('doc_freq_ratio', ascending=False)

Now the only method and the one that made most sense to me to take out too common words is basically just defining a threshold and see which words are too rare (like if it appears only 2-3 times in the whole dataset) or too much (in this case too much can be like appearing in more than 40-60% of the descriptions), you can try different values of the two initial thresholds (the one I saw looks the best would be 0.0005 for the low and 0.55 for the high)

In [ ]:
min_ratio = 0.0003
max_ratio = 0.50

vocab = set(
    df_table[
        (df_table['doc_freq_ratio'] > min_ratio) &
        (df_table['doc_freq_ratio'] < max_ratio)
    ]['word']
)

campaigns['description_processed'] = campaigns['lemmatized'].apply(
    lambda doc: [w for w in doc if w in vocab]
)

print(df_table[df_table['doc_freq_ratio'] >= max_ratio])
df_table[df_table['doc_freq_ratio'] <= min_ratio]
campaigns = campaigns.drop(columns=['lemmatized'])

KeyError: 'lemmatized'

### Now we work on the data specific category by category

In [71]:
df = campaigns

#### 1. Identification of words appearing in more than 40% of documents

In [76]:

df_film = df[df['category'] == 'Film & Video']
docs = df_film["description_processed"]

N = len(docs)
df_counter = Counter()

for doc in docs:
    df_counter.update(set(doc))

df_table = pd.DataFrame({
    "word": list(df_counter.keys()),
    "doc_freq": list(df_counter.values())
})

df_table["doc_freq_ratio"] = df_table["doc_freq"] / N
high_freq_words = df_table[df_table["doc_freq_ratio"] > 0.5]
high_freq_words = high_freq_words.sort_values("doc_freq_ratio", ascending = False)
high_freq_words

           word  doc_freq  doc_freq_ratio
65         film      1689        0.839881
191  production      1333        0.662854
358        love      1062        0.528095
96         take      1045        0.519642
14         team      1024        0.509199
222    director      1024        0.509199
219         see      1014        0.504227
461        many      1012        0.503232

In [ ]:
extra_stopwords_film = set(high_freq_words["word"].tolist())
texts_film = df_film["description_processed"].tolist()

texts_film_filtered = [
    [word for word in text if word not in extra_stopwords_film]
    for text in texts_film
]